name: Generate Changelog
description: Generate changelog from conventional commits using cocogitto
author: DataRoad Inc.

inputs:
  release-tag:
    description: 'Release tag (e.g., v0.0.1)'
    required: true
  output-file:
    description: 'File to write changelog to'
    required: false
    default: 'CHANGELOG.md'

runs:
  using: composite
  steps:
    - name: Setup Cocogitto
      uses: ./.github/actions/setup-cocogitto

    - name: Generate changelog
      shell: bash
      run: |
        # Call the standalone script for easier local testing
        "${GITHUB_WORKSPACE:-.}/.bash/gha-generate-changelog.sh" \
          "${{ inputs.output-file }}" \
          "${{ inputs.release-tag }}"

